apiVersion : apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app : nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      project: k8s
  template:
    metadata:
      labels:
        project: k8s   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env  : prod
    owner: VladislavProkuda
spec:
  selector:
    project: k8s    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer
