apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
  labels:
    app : my-k8s1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: ukr1
  template:
    metadata:
      labels:
        project: ukr1   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : ukr1-web
          image: vladislavprokuda/k8sphp1:latest
          ports:
            - containerPort: 80
